name: Check Pull Request Title Format

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title format
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          echo "Pull request title: $pr_title"
          
          regex="^VM-[0-9]+ .+"
          
          # Проверяем, соответствует ли pull request title заданному формату
          if [[ ! "$pr_title" =~ $regex ]]; then
            echo "Error: Pull request title does not match the required format: 'VM-<id> <task title>'"
            exit 1
          else
            echo "Pull request title is in the correct format"
          fi
